#!/usr/bin/env python3

import unittest
import testlib
import subprocess
import stub_gen
import tempfile
import change
import json


class MockIOStream:
    def __init__(self):
        self._data = ""

    def write(self, data):
        self._data += data

    def close(self):
        pass

    def getvalue(self):
        return self._data


class TestStubGen(unittest.TestCase):
    def test_write_class(self):
        data = {
            "field1": 1,
            "field2": "2",
            "field3": "value"
        }
        exp_value = """
class TestClass:
    def __init__(self, field1: int=None, field2: str=None, field3: str=None):
        self.field1: int = field1
        self.field2: str = field2
        self.field3: str = field3

"""
        out = MockIOStream()
        stub_gen.write_class(out, data, "TestClass")
        self.assertEqual(exp_value, out.getvalue())

    def test_stub_gen_cli(self):
        data = b"""{
            "foo": "bar",
            "baz": 1
        }"""
        exp_value = """#/usr/bin/env python3
# Generated by Stub Gen (version: 0)

class Object:
    def __init__(self, foo: str=None, baz: int=None):
        self.foo: str = foo
        self.baz: int = baz

"""

        script_path = testlib.rootpath("../stub_gen.py")
        process = subprocess.run([script_path, "--stdin"], input=data, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
        self.assertEqual(0, process.returncode, "Process non-zero exit status %d\n\nSTDERR:\n%s" % (process.returncode, process.stderr.decode("utf-8")))
        self.assertEqual(exp_value, process.stdout.decode("utf-8"))

        with tempfile.NamedTemporaryFile("w") as tmp:
            process = subprocess.run([script_path, "--stdin", "--output-file", tmp.name], input=data, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
            with open(tmp.name, "r") as fh:
                self.assertEqual(exp_value, fh.read())


    def test_stub_object(self):
        with open(testlib.rootpath("data/change.json"), "r") as fh:
            json_data = json.loads(fh.read())
        obj = change.Change(**json_data)
        for key, value in json_data.items():
            self.assertEqual(obj.__getattribute__(key), value)


if __name__ == "__main__":
    unittest.main()