#!/usr/bin/env python3

import unittest
import testlib
import subprocess
import stub_gen
import tempfile
import change
import json
from ddt import ddt, data, unpack


class MockIOStream:
    def __init__(self):
        self._data = ""

    def write(self, data):
        self._data += data

    def close(self):
        pass

    def getvalue(self):
        return self._data


@ddt
class TestStubGen(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.maxDiff = None

    @data(
        ({
                "field1": 1,
                "field2": "2",
                "field3": "value",
                "field4": False
        },"""
class TestClass:
    def __init__(self, field1: int=None, field2: str=None, field3: str=None, field4: bool=None):
        self.field1: int = field1
        self.field2: str = field2
        self.field3: str = field3
        self.field4: bool = field4

"""),
        ({
            "value": 1,
            "nested_value": {
                "field1": "11",
                "field2": "12",
                "other": {
                    "f1": 1,
                    "f2": 2
                }
            }
        },"""
class Other:
    def __init__(self, f1: int=None, f2: int=None):
        self.f1: int = f1
        self.f2: int = f2


class Nested_value:
    def __init__(self, field1: str=None, field2: str=None, other: Other=None):
        self.field1: str = field1
        self.field2: str = field2
        self.other: Other = other


class TestClass:
    def __init__(self, value: int=None, nested_value: Nested_value=None):
        self.value: int = value
        self.nested_value: Nested_value = nested_value

"""))
    @unpack
    def test_write_class(self, input, expected):
        out = MockIOStream()
        stub_gen._write_class(out, input, "TestClass")
        self.assertEqual(expected, out.getvalue())


    def test_stub_gen_cli(self):
        data = b"""{
            "foo": "bar",
            "baz": 1
        }"""
        exp_value = """# Generated by Stub Gen (version: 0)

class Object:
    def __init__(self, foo: str=None, baz: int=None):
        self.foo: str = foo
        self.baz: int = baz

"""

        script_path = testlib.rootpath("../stub_gen.py")
        process = subprocess.run([script_path, "--stdin"], input=data, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
        self.assertEqual(0, process.returncode, "Process non-zero exit status %d\n\nSTDERR:\n%s" % (process.returncode, process.stderr.decode("utf-8")))
        self.assertEqual(exp_value, process.stdout.decode("utf-8"))

        with tempfile.NamedTemporaryFile("w") as tmp:
            process = subprocess.run([script_path, "--stdin", "--output-file", tmp.name], input=data, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
            with open(tmp.name, "r") as fh:
                self.assertEqual(exp_value, fh.read())


    def test_stub_object(self):
        with open(testlib.rootpath("data/change.json"), "r") as fh:
            json_data = json.loads(fh.read())
        obj = change.Change(**json_data)
        for key, value in json_data.items():
            self.assertEqual(obj.__getattribute__(key), value)


if __name__ == "__main__":
    unittest.main()