#/usr/bin/env python3
# Generated by Stub Gen (version: 0)

class Owner:
    def __init__(self, name: str=None, email: str=None, username: str=None):
        self.name: str = name
        self.email: str = email
        self.username: str = username


class Change:
    def __init__(self, project: str=None, branch: str=None, id: str=None, number: int=None, subject: str=None, owner: Owner=None, url: str=None, commitMessage: str=None, createdOn: int=None, lastUpdated: int=None, open: bool=None, status: str=None):
        self.project: str = project
        self.branch: str = branch
        self.id: str = id
        self.number: int = number
        self.subject: str = subject
        self.owner: Owner = owner
        self.url: str = url
        self.commitMessage: str = commitMessage
        self.createdOn: int = createdOn
        self.lastUpdated: int = lastUpdated
        self.open: bool = open
        self.status: str = status

